name: Deploy to OCI
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Pymetory
        uses: appleboy/ssh-action@v1
        with:
          host: SERVIDOR
          username: ubuntu
          key: ${{ secrets.OCI_SSH_KEY }}
          port: 443
          script: |
            cd /var/www/pymetory
            git pull origin main
            sudo -u www-data php artisan view:clear
            sudo -u www-data php artisan config:clear
            php artisan optimize 2>&1 | tail -3
            sudo systemctl reload nginx
